import { KeyboardWindowLogic } from "keyboard_service.slint";
export component KnobCapture inherits FocusScope {
    in-out property <string> text: "";
    in property <bool> cursors: false;
    hbox := HorizontalLayout {
        alignment: center;
        spacing: 0px;
        if cursors: Image {
            visible: root.has-focus;
            source: @image-url("assets/cursor_right.png");
        }
        rect := Rectangle {
            text := Text {
                text <=> root.text;
                color: root.has-focus ? Blinker.white(root.accessible-expanded) : black;
                horizontal-alignment: TextHorizontalAlignment.center;
                vertical-alignment: TextVerticalAlignment.center;
            }
            background: root.has-focus ? Blinker.ntransparent(root.accessible-expanded) : transparent;
        }
        if cursors: Image {
            visible: root.has-focus;
            source: @image-url("assets/cursor_left.png");
        }
    }
    key-pressed(event) => {
        if (!self.accessible-expanded) {
            return EventResult.reject;
        }
        if (event.text == Key.Tab || event.text == Key.RightArrow) {
            self.accessible-action-increment();
            return EventResult.accept;
        }
        if (event.text == Key.Backtab || event.text == Key.LeftArrow) {
            self.accessible-action-decrement();
            return EventResult.accept;
        }
        return EventResult.reject;
    }
    key-released(event) => {
        if (event.text == Key.Return) {
            self.accessible-expanded = !self.accessible-expanded;
            self.accessible-action-default();
            return EventResult.accept;
        }
        return EventResult.reject;
    }
}

export component SpinBox inherits KnobCapture {
    in-out property <float> value: 0.0;
    in property <float> step: 1.0;
    in property <float> min: -9999.0;
    in property <float> max: 9999.0;

    text: value.to-fixed(4);

    accessible-role: AccessibleRole.spinbox;

    accessible-action-increment => {
        value = Math.min(value + step, max);
    }

    accessible-action-decrement => {
        value = Math.max(value - step, min);
    }
}


export component KnobButton inherits FocusScope {
    in-out property <string> text;
    in property <bool> cursors: false;
    hbox := HorizontalLayout {
        alignment: center;
        spacing: 0px;
        if cursors: Image {
            visible: root.has-focus;
            source: @image-url("assets/cursor_right.png");
        }
        rect := Rectangle {
            text := Text {
                text <=> root.text;
                color: root.has-focus ? white : black;
                horizontal-alignment: TextHorizontalAlignment.center;
                vertical-alignment: TextVerticalAlignment.center;
            }
            background: root.has-focus ? black : transparent;
        }
        if cursors: Image {
            visible: root.has-focus;
            source: @image-url("assets/cursor_left.png");
        }
    }
    key-released(event) => {
        if (event.text == Key.Return) {
            self.accessible-action-default();
            return EventResult.accept;
        }
        return EventResult.reject;
    }
    accessible-role: AccessibleRole.button;
}

export component KnobImageButton inherits FocusScope {
    in-out property <image> image;
    in property <bool> cursors: false;
    hbox := HorizontalLayout {
        alignment: center;
        spacing: 0px;
        if cursors: Image {
            visible: root.has-focus;
            source: @image-url("assets/cursor_right.png");
        }
        rect := Rectangle {
            image := Image {
                source <=> root.image;
                colorize: root.has-focus ? white : black;
            }
            background: root.has-focus ? black : transparent;
        }
        if cursors: Image {
            visible: root.has-focus;
            source: @image-url("assets/cursor_left.png");
        }
    }
    key-released(event) => {
        if (event.text == Key.Return) {
            self.accessible-action-default();
            return EventResult.accept;
        }
        return EventResult.reject;
    }
    accessible-role: AccessibleRole.button;
}

export component KnobLineEdit inherits FocusScope {
    in-out property <string> text;
    in property <InputType> input-type;
    VerticalLayout {
        spacing: 0px;
        HorizontalLayout {
            alignment: stretch;
            line_edit := TextInput {
                horizontal-stretch: 1;
                text <=> root.text;
                single-line: true;
                input-type <=> root.input-type;
            }
            forward-focus: keyboard_button;
            keyboard_button := KnobImageButton {
                vertical-stretch: 0;
                horizontal-stretch: 0;
                image: @image-url("assets/keyboard.png");
                accessible-action-default => {
                    line_edit.focus();
                    KeyboardWindowLogic.open();
                    KeyboardWindowLogic.window_offset_y = -line_edit.absolute-position.y;
                }
                cursors: true;
            }
        }
        Rectangle {
            height: 1px;
            background: black;
        }
    }
}



export global Blinker {
    in-out property <bool> high: false;

    public pure function white(enable: bool) -> color {
        return enable && high ? Colors.black : Colors.white;
    }
    public pure function black(enable: bool) -> color {
        return enable && high ? Colors.white : Colors.black;
    }
    public pure function transparent(enable: bool) -> color {
        return enable && high ? Colors.black : Colors.transparent;
    }
    public pure function ntransparent(enable: bool) -> color {
        return enable && high ? Colors.transparent : Colors.black;
    }
}

export global Counter {
    in-out property <int> count: 0;
}

export global PlantValue {
    in-out property <int> FanNum: 30;
    in-out property <int> LightNum: 50;
    in-out property <int> WaterNum: 30;
    in-out property <int> HumNum: 20;
    in-out property <int> HumTarget: 70;
    in-out property <int> TempNum: 24;
    in-out property <int> TempTarget: 27;
    in-out property <int> CoolNum: 26;
    in-out property <int> OutTempNum: 18;
    in-out property <int> OutHumNum: 30;
}