export component IconBox {
    in property <string> text: "test";
    in property <image> icon: @image-url("icons/test.png");
    Rectangle {
        width: 38px;
        height: 12px;
        HorizontalLayout {
            width: 100%;
            height: 100%;

            spacing: 4px;
            
            alignment: center;

            Image {
                width: 12px;
                height: 12px;
                source: root.icon;
                accessible-label: "icon";
            }
            
            Text {
                text: root.text;
                overflow: elide; 
            }
        }
    }
}

export component DashBox inherits Rectangle {
    border-width: 1px;
    border-color: black;
    width: 66%;
    GridLayout {
        spacing-vertical: 2px;
        Row {
            IconBox {}
            IconBox {}
        }
        Row {
            IconBox {}
            IconBox {}
        }
        Row {
            IconBox {}
            IconBox {}
        }
    }

}

export component DashBoard {
    Rectangle {
        VerticalLayout {
            alignment: stretch;
            Text {
                wrap: TextWrap.word-wrap;
                text: "<식물이름>";
            }
            Rectangle {
                HorizontalLayout {
                    DashBox {}
                    IconBox {}
                }
            }

        }
    }
}
