import { Blinker, Counter } from "components.slint";

export component IconBox {
    in property <string> text: "00";
    in property <image> icon: @image-url("assets/snow.png");
    in property <bool> is_long: false;
    Rectangle {
        width: (is_long)?44px:30px;
        height: 12px;
        HorizontalLayout {
            width: 100%;
            height: 100%;
            spacing: 3px;
            
            alignment: center;

            Image {
                width: 12px;
                height: 12px;
                source: root.icon;
                accessible-label: "icon";
            }
            
            Text {
                //viewr사용시 height 주석처리
                //height: 8px;
                vertical-alignment: center;
                text: root.text;
                overflow: elide; 
            }
        }
    }
}

export component FanBox inherits IconBox {
    in property <int> num: 30;
    icon: (Math.mod(Counter.count, (120-num)/10)==0) ? @image-url("assets/fan_a.png") : @image-url("assets/fan_b.png");
    text: num + "%";
}

export component LightBox inherits IconBox {
    icon: @image-url("assets/light.png");
    in property <int> num: 50;
    in property <int> target: 70;
    is_long: true;
    text: num + "/"+ target + "%";
}

export component WaterBox inherits IconBox {
    icon: @image-url("assets/humidity.png");
    in property <int> num: 30;
    text: num + "%";
}
export component HumBox inherits IconBox {
    icon: @image-url("assets/humidity_b.png");
    in property <int> num: 20;
    in property <int> target: 60;
    is_long: true;
    text: num + "/"+ target + "%";
}

export component TempBox inherits IconBox {
    icon: @image-url("assets/thermometer.png");
    in property <int> num: 24;
    in property <int> target: 27;
    is_long: true;
    text: num + "/"+ target+ "°C";
}

export component CoolBox inherits IconBox {
    icon: @image-url("assets/snow.png");
    in property <int> num: 15;
    text: num + "%";
}
export component DashBox inherits Rectangle {
    border-width: 1px;
    border-color: black;
    border-radius: 4px;
    GridLayout {
        spacing: 2px;
        padding: 2px;
        Row {
            FanBox {}
            LightBox {}
        }
        Row {
            WaterBox {}
            HumBox {}
        }
        Row {
            CoolBox {}
            TempBox {}
        }
    }

}

export component DashBoard inherits VerticalLayout {
    in property <int> day: 20;
    alignment: stretch;
    vertical-stretch: 1.0;
    spacing: 1px;
    HorizontalLayout {
        Text {
            height: 8px;
            wrap: TextWrap.word-wrap;
            text: "<식물이름>";
        }
        Text {
            height: 8px;
            horizontal-alignment: left;
            text: "-DAY " + day;
        }
    }
        HorizontalLayout {
            vertical-stretch: 1.0;
            DashBox {}
            VerticalLayout {
                spacing: 2px;
                IconBox {}
                IconBox {}
            }

        }
}
