import { Blinker, Counter, KnobButton, KnobImageButton, KnobLineEdit} from "components.slint";
import { LineEdit } from "std-widgets.slint";

export component IconBox {
    in property <string> text: "00";
    in property <image> icon: @image-url("assets/snow.png");
    in property <bool> is_long: false;
    in property <bool> light: false;

    Rectangle {
        width: (is_long)?44px:32px;
        height: 12px;
        HorizontalLayout {
            width: 100%;
            height: 100%;
            spacing: 3px;
            alignment: space-between;

            Image {
                width: 12px;
                height: 12px;
                source: root.icon;
                accessible-label: "icon";
                horizontal-alignment: left;
            }
            
            Text {
                //viewr사용시 height 주석처리
                //height: 8px;
                vertical-alignment: center;
                horizontal-alignment: right;
                text: root.text;
                overflow: elide; 
            }
        }
    }
}

export struct Plant {
    Fan: int,
    Light: int,
    Water: int,
    Hum: int,
    HumTarget: int,
    Temp: int,
    TempTarget: int,
    Cool: int,
    OutTemp: int,
    OutHum: int,
}

export struct PlantName {
    name: string,
    day: int,
}

export global PlantValue { 
    in-out property <Plant> plant: {
        Fan: 50,
        Light: 70,
        Water: 40,
        Hum: 60,
        HumTarget: 65,
        Temp: 24,
        TempTarget: 22,
        Cool: 30,
        OutTemp: 28,
        OutHum: 55,
    };

    callback censor;
}

export global PlantNameValue {
    in-out property <PlantName> plantname: {name:"flower", day:55};
    callback name;
}

export component FanBox inherits IconBox {
    in property <int> num: PlantValue.plant.Fan;
    icon: (Math.mod(Counter.count, (120-num)/10)==0) ? @image-url("assets/fan_a.png") : @image-url("assets/fan_b.png");
    text: num + "%";
}

export component LightBox inherits IconBox {
    icon: @image-url("assets/light.png");
    in property <int> num: PlantValue.plant.Light;
    text: num + "%";
    is_long: true;
    light: true;
}

export component WaterBox inherits IconBox {
    icon: @image-url("assets/humidity.png");
    in property <int> num: PlantValue.plant.Water;
    text: num + "%";
}
export component HumBox inherits IconBox {
    in property <int> num: PlantValue.plant.Hum;
    in property <int> target: PlantValue.plant.HumTarget;
    icon: Math.mod(Counter.count, (120-Math.abs(num - target)/10))==0?@image-url("assets/humidity_b.png"): @image-url("assets/humidity.png");
    is_long: true;
    text: num + "/"+ target + "%";
}

export component TempBox inherits IconBox {
    icon: @image-url("assets/thermometer.png");
    in property <int> num: PlantValue.plant.Temp;
    in property <int> target: PlantValue.plant.TempTarget;
    is_long: true;
    text: num + "/"+ target+ "°C";
}

export component CoolBox inherits IconBox {
    icon: @image-url("assets/snow.png");
    in property <int> num: PlantValue.plant.Cool;
    text: num + "%";
}

export component OutTemp inherits IconBox {
    icon: @image-url("assets/thermometer.png");
    in property <int> num: PlantValue.plant.OutTemp;
    text: num + "°C";
}
export component OutHum inherits IconBox {
    icon: @image-url("assets/humidity.png");
    in property <int> num: PlantValue.plant.OutHum;
    text: num + "%";
}
export component DashBox inherits Rectangle {
    border-width: 1px;
    border-color: black;
    border-radius: 4px;
    GridLayout {
        spacing: 2px;
        padding: 2px;
        Row {
            FanBox {}
            LightBox {}
        }
        Row {
            WaterBox {}
            HumBox {}
        }
        Row {
            CoolBox {}
            TempBox {}
        }
    }

}



export component DashBoard inherits VerticalLayout {
    in property <int> day: 20;
    alignment: stretch;
    vertical-stretch: 1.0;
    spacing: 1px;
    HorizontalLayout {
        Text {
            wrap: TextWrap.word-wrap;
            text: PlantNameValue.plantname.name;
        }
        Text {
            horizontal-alignment: right;
            text: "-DAY " + PlantNameValue.plantname.day;
        }
    }
        HorizontalLayout {
            vertical-stretch: 1.0;
            DashBox {}
            VerticalLayout {
                spacing: 2px;
                OutTemp {}
                OutHum {}
            }

        }
}
