import { Button, VerticalBox, TabWidget, ScrollView, HorizontalBox } from "std-widgets.slint";
import "./dalmoori.ttf";
import {DashBoard} from "dash.slint";
import {KnobCapture, SpinBox, Blinker} from "components.slint";

component SmallTabWidget inherits VerticalLayout {
    alignment: stretch;
    in property <[{name: string, id: int}]> tabs: [
        {name: "대시보드", id: 0},
        {name: "menu", id: 1}
    ];
    in-out property <int> selected: 0;
    tab_bar := HorizontalLayout {
        alignment: LayoutAlignment.start;
        KnobCapture { // the tab selector
            height: 8px;
            text: root.tabs[root.selected].name;
            accessible-role: AccessibleRole.tab-list;
            accessible-action-increment => {
                root.selected = Math.mod(root.selected + 1, root.tabs.length);
            }
            accessible-action-decrement => {
                root.selected = Math.mod(root.selected + root.tabs.length - 1, root.tabs.length);
            }
        }
    }
    Rectangle { //가로줄
        height: 1px;
        background: black;
    }
    DashBoard{}
    VerticalLayout {
        visible: root.selected == 1;
        Text {
            wrap: TextWrap.word-wrap;
            text: "menu screen";
        }
        SpinBox {
            min: -1;
            max: 25;
            step: 0.01;
        }
    }
}

export component EmbeddedUI inherits Window {
    width: 128px;
    height: 64px;
    default-font-family: "dalmoori";
    default-font-size: 8px;
    SmallTabWidget {}


    timer := Timer {
        interval: 0.5s;
        triggered => {
            Blinker.high = !Blinker.high;
        }
    }
}