export component IconBox {
    in property <string> text: "test";
    in property <image> icon: @image-url("assets/snow.png");
    Rectangle {
        width: 38px;
        height: 12px;
        HorizontalLayout {
            width: 100%;
            height: 100%;
            spacing: 3px;
            
            alignment: center;

            Image {
                width: 12px;
                height: 12px;
                source: root.icon;
                accessible-label: "icon";
            }
            
            Text {
                //height: 8px;
                vertical-alignment: center;
                text: root.text;
                overflow: elide; 
            }

        }
    }
}